# Generated by Django 3.0.8 on 2020-08-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['lecture'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['semester'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=128)),
                ('faculty', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('lecture', models.ManyToManyField(blank=True, to='distribution.Lecture')),
            ],
            options={
                'ordering': ['lecturer'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.ImageField(upload_to='distribution/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='distribution.Lecture')),
                ('lecturer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='distribution.Lecturer')),
                ('semester', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='distribution.Semester')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=256, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('anon', models.BooleanField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('author_security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author_security', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.Lecturer')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
